version: '1.0'
pipeline:
  build:
    stage: build
    image: kivy/buildozer:latest
    steps:
      - name: install_java
        commands:
          - apt update && apt install -y openjdk-17-jdk
      - name: build_apk
        commands:
          - buildozer android debug
    artifacts:
      - name: apk
        path: bin/*.apk
        expire_in: 7d
